project_id = "wfuctevpojkhcbbegzvh"

[functions.poster-ai]
verify_jwt = false

[functions.fetch-streets]
verify_jwt = false

[functions.geonames-search]
verify_jwt = false

[functions.render-poster]
verify_jwt = false
